repos:

- repo: https://github.com/pycqa/isort
  rev: 6.0.0
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.1
  hooks:
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
